import jwt
import datetime

from fastapi import APIRouter, Body, Request, Response, HTTPException, status, Header, Depends
from fastapi.encoders import jsonable_encoder
from typing import List

from models import Inmueble

secret_key = 'W0bkRHQVe8P[kF[Nx|11]R{|rWL"VxXgkafD:j;.2;Uw7yk>^6_12_J*`[Iik{+'
use_auth = True

# For now, I am not returning anything here, if we wanted to see capabilities we would
async def validate_token(access_token: str = Header(default="")):
    if use_auth:
        try:
            # Decoding fails if token is invalid or expired
            decoded_token = jwt.decode(access_token, key=secret_key, algorithms=['HS256'])
        # Depending on whether expiry time is included in access tokens generated by the auth service, may need to check how long it has been since issue
        except (jwt.exceptions.DecodeError, jwt.exceptions.InvalidSignatureError):
            raise HTTPException(status_code=401, detail="Invalid token")
        except jwt.exceptions.ExpiredSignatureError:
            raise HTTPException(status_code=401, detail="Expired token")

router = APIRouter(dependencies=[Depends(validate_token)])

@router.post("/", response_description="Create a new inmueble", status_code=status.HTTP_201_CREATED, response_model=Inmueble)
def create_inmueble(request: Request, inmueble: Inmueble = Body(...)):
    inmueble = jsonable_encoder(inmueble)
    if inmueble.get('_id'):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="ID field cannot be set manually")
    new_inmueble = request.app.database['inmuebles'].insert_one(inmueble)
    created_inmueble = request.app.database['inmuebles'].find_one(
        {'_id': new_inmueble.inserted_id}
    )
    return created_inmueble

@router.get("/", response_description="Get all inmuebles", response_model=List[Inmueble])
def get_all_inmuebles(request: Request):
    inmuebles = list(request.app.database['inmuebles'].find())
    return inmuebles

@router.get("/{id}", response_description="Get an inmueble by id", response_model=Inmueble)
def get_inmueble(id: str, request: Request):
    if (inmueble := request.app.database["inmuebles"].find_one({'_id': id})) is not None:
        return inmueble
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Inmueble with ID {} does not exist".format(id))

# They will already have the full object when they get here, so it's OK to just put the full object
@router.put("/{id}", response_description="Edit an inmueble by ID", response_model=Inmueble)
def edit_inmueble(id: str,request: Request, inmueble: Inmueble = Body(...)):
    inmueble = jsonable_encoder(inmueble)
    if inmueble['_id'] != id:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="ID field cannot be edited")
    edit_result = request.app.database['inmuebles'].update_one({'_id': id}, {'$set': inmueble})
    if edit_result.modified_count == 0:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Inmueble with ID {} does not exist".format(id))
    if (inmueble := request.app.database['inmuebles'].find_one({'_id': id})) is not None:
        return inmueble
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Inmueble with ID {} does not exist".format(id))

@router.delete("/{id}", response_description="Delete an inmueble by id")
def delete_inmueble(id: str, request: Request, response: Response):
    if request.app.database['inmuebles'].delete_one({"_id": id}).deleted_count == 1:
        response.status_code = status.HTTP_204_NO_CONTENT
        return response
    raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Inmueble with ID {} does not exist".format(id))
